name: GenAI Basic Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ai-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # AI-powered code formatting
      - name: AI Code Formatting
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
          commit_message: "AI-powered code formatting"
          
      # AI-powered code review comments
      - name: AI Code Review
        uses: coderabbitai/ai-pr-reviewer@latest
        
      # Simple checks for demo
      - name: Pipeline Status
        run: |
          echo "GenAI Pipeline completed successfully!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"


# name: Basic Test Pipeline

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Run Basic Check
#         run: |
#           echo "Running basic checks..."
#           echo "Repository: ${{ github.repository }}"
#           echo "Branch: ${{ github.ref }}"
#           echo "All checks passed!"
